[project]
name = "syuct-course-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4==4.13.3",
    "ddddocr==1.5.6",
    "lxml>=6.0.1",
    "pillow==11.1.0",
    "requests==2.32.3",
]
